### ISSUE TITLE
Update spacing and add network icons to Achievements list 

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#2372] opened 2022-10-04 15:26 UTC
In 0.16.5a5d93f1, Achievement images are touching one another... 

<img width="386" alt="Screen Shot 2022-10-04 at 11 25 31 AM" src="https://user-images.githubusercontent.com/7005061/193860846-891e3790-61b6-4ede-9fd7-367a49986def.png">

vs. buffer in NFT tab

<img width="440" alt="Screen Shot 2022-10-04 at 11 11 38 AM" src="https://user-images.githubusercontent.com/7005061/193860849-204efb75-ddf4-400f-9850-a9e0f2a96cf1.png">

Design reference - https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=13226%3A243293

**Comment by jagodarybacka** [comment] 2022-10-05 14:03
I can't reproduce it. Closing for now
![image](https://user-images.githubusercontent.com/20949277/194079957-d56d6994-1abe-436a-b19e-d78caf3a6ea0.png)

**Closed by jagodarybacka** 2022-10-05 14:03 UTC
Labels: 🐛 bug
