### ISSUE TITLE
Not able to send MATIC on Polygon

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#1902] opened 2022-08-08 07:17 UTC
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/1005505372792029184

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

User tried to send MATIC on Polygon

### What did not work?

Transactions remained pending. After the user did a re-install he was able to send MATIC.

Original logs:
[logs_v0_14_2__2022-08-07T16_34_4705_30.txt](https://github.com/tallycash/extension/files/9279615/logs_v0_14_2__2022-08-07T16_34_4705_30.txt)

![20220806_212649](https://user-images.githubusercontent.com/71384922/183361287-8264c676-61aa-4225-8183-c70edb2262b8.jpg)

### Version

Community Edition v0.14.2

**Comment by jagodarybacka** [comment] 2022-08-09 12:43
I can't reproduce the issue. I tried sending MATIC and it is working fine, closing for now.

**Closed by jagodarybacka** 2022-08-09 12:43 UTC
Labels: 🐛 bug, 👩‍⚕️ triage
