### ISSUE TITLE
'Max' button re-appearing when doing a 'swap to' - 'swap from' flip

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#1903] opened 2022-08-08 07:46 UTC
### Discord Discussion Link

na

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Flip the 'swap to' - 'swap from' assets

### What did not work?

The 'max' option that was removed re-appears in the 'swap from' field when using the flip button in the middle.
<img width="367" alt="Screen Shot 2022-08-08 at 09 44 28" src="https://user-images.githubusercontent.com/71384922/183366587-b2e48fc3-ef11-47af-916a-bd9ad150d7d8.png">

<img width="368" alt="Screen Shot 2022-08-08 at 09 44 33" src="https://user-images.githubusercontent.com/71384922/183366622-7d17d3ea-f9a9-45e8-a56b-7b78162a338f.png">

### Version

Community Edition v0.14.2

**Comment by jagodarybacka** [comment] 2022-08-10 09:06
@Naxsun by design "max" button is only hidden for base assets - MATIC on Polygon, ETH on Ethereum - looking at the screenshot it is fine to show "max" for USDC. Is it visible for MATIC if you click flip button one more time?

**Comment by jagodarybacka** [comment] 2022-10-19 13:22
Working as expected so I'm closing the issue

**Closed by jagodarybacka** 2022-10-19 13:22 UTC
Labels: 🐛 bug, 👩‍⚕️ triage
