### ISSUE TITLE
Transaction details Amount --> MATIC not ETH

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#1768] opened 2022-07-08 01:33 UTC
Updates:
- txn details - "Amount" is in ETH, but should be be MATIC

https://polygonscan.com/tx/0x0816b2615a4ab9e77b59b319418047d505a5571b107dbb783303da62eecbfd94

![image](https://user-images.githubusercontent.com/7005061/177898311-819fdd62-0e48-4078-8d27-f559c46b9b99.png)

![image](https://user-images.githubusercontent.com/7005061/177898467-147cf4e8-2217-4916-986e-d9bc507c1c8f.png)

**Comment by Shadowfiend** [comment] 2022-07-09 03:35
Duplicate of #1731, which has an associated PR.

**Closed** 2022-07-09 03:35 UTC
Labels: 🐛 bug, ⚠️ medium severity, Polygon
