### ISSUE TITLE
dApp 'connect from' - text overflow, not wrapped

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#2240] opened 2022-09-19 09:14 UTC
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/1021337799435231252

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Connect to Galxe

### What did not work?

Text overflow

On users Windows:
"horizontal scroll bar does not appear, but horizontal scrolling happens "
Windows 11, Latest Chrome, Tally Ho! v0.16.0_93902cc 
![image](https://user-images.githubusercontent.com/71384922/190985908-199ebe01-f617-4cef-8596-5175f564f67b.png)

On Mac Nax:
<img width="383" alt="Screen Shot 2022-09-19 at 11 11 12" src="https://user-images.githubusercontent.com/71384922/190985630-7c36faaf-92df-4a02-ad1c-02ac41ec4449.png">

### Version

v0.16.0

**Comment by greg-nagy** [comment] 2022-09-19 15:27
duplicate of #2243

**Closed by greg-nagy** 2022-09-19 15:27 UTC
Labels: 🐛 bug, 👩‍⚕️ triage
