### ISSUE TITLE
Wallet token balance and $ balance shown as 0 

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#915] opened 2022-01-30 18:35 UTC
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/936691219294220298

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Load a wallet in Tally through a MM seed.

### What did not work?

The ETH balance (0.009 ETH) and the $ balance ($22) were not displayed.

The wallet activity, send and receive is shown. There is also a '0 ETH' incoming transaction shown, that is not displayed by MM. Have not yet requested the users 
<img width="301" alt="Screen Shot 2022-01-30 at 19 29 19" src="https://user-images.githubusercontent.com/71384922/151712468-5a083059-a489-4291-98b0-e2bb3097e255.png">
<img width="294" alt="Screen Shot 2022-01-30 at 19 29 24" src="https://user-images.githubusercontent.com/71384922/151712472-b103ca71-486c-4269-8534-66172f239e36.png">
<img width="289" alt="Screen Shot 2022-01-30 at 19 29 31" src="https://user-images.githubusercontent.com/71384922/151712475-8044e258-6838-4afb-8856-2ce7a65b7f43.png">
<img width="297" alt="Screen Shot 2022-01-30 at 19 29 41" src="https://user-images.githubusercontent.com/71384922/151712478-9b81c8ad-1e53-4d9e-a25e-f302ff968cfd.png">

Similar issue: Discord link: https://discord.com/channels/808358975287722045/888500174685614090/936308719044657182

The user has ETH and WETH in this wallet. ETH is shown as a line item, but the balance is not there on both the wallet and the overview page. There is also no ETH price loaded. Subsequently the ETH $ value is not taken into account in the $ balances.

![image](https://user-images.githubusercontent.com/71384922/151712579-d7cb0f75-9410-43b5-ae84-1ca3a52a0f4b.png)

### Version

Community Edition v0.11.0

**Comment by Shadowfiend** [comment] 2022-01-30 20:55
Believe a fix for this just landed in #912, and that this effectively a dupe of #813.

**Closed** 2022-02-08 23:09 UTC
Labels: 🐛 bug, 👩‍⚕️ triage
