### ISSUE TITLE
'Sign Transaction' pop-up is lacking basic txn price info

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#715] opened 2021-12-17 00:53 UTC
Let's discuss.

Spend Amount is "0.02" - we need to provide units

No USD equivalent given for gas spend

<img width="383" alt="Screen Shot 2021-12-16 at 7 20 06 PM" src="https://user-images.githubusercontent.com/7005061/146470452-337be51e-1fb6-4690-8a7d-9ff5d7fb9db9.png">

<img width="412" alt="Screen Shot 2021-12-16 at 7 40 44 PM" src="https://user-images.githubusercontent.com/7005061/146470456-79830d50-d4f1-491b-8061-aa264effa060.png">

<img width="382" alt="Screen Shot 2021-12-16 at 7 47 49 PM" src="https://user-images.githubusercontent.com/7005061/146470457-3a5cd513-b96f-4d06-a463-059dc9b3dd4b.png">

**Comment by VladUXUI** [comment] 2021-12-17 08:47
fwiw this is not a design bug. I think front-end needs a bit more tlc
![image](https://user-images.githubusercontent.com/80846886/146516068-e4d13876-fdf5-4900-8c4e-6df75e24d0ef.png)

**Comment by henryboldi** [comment] 2021-12-17 21:42
> No USD equivalent given for gas spend

This part in particular is a duplicate of #656

**Comment by henryboldi** [comment] 2021-12-17 21:42
Duplicate of #689

**Comment by mhluongo** [comment] 2021-12-22 22:18
Closed by #730

**Closed by mhluongo** 2021-12-22 22:18 UTC
Labels: 🐛 bug, 👥 duplicate, ⚠️ medium severity
