### ISSUE TITLE
Adding addresses derived from 12 word recovery phrase not working

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#1055] opened 2022-02-28 12:59 UTC
### Discord Discussion Link

https://discord.com/channels/808358975287722045/944337346684391474/947700364398985246

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

User wanted to create additional addresses derived from a MM created 12 word recovery phrase

### What did not work?

When clicking Add address there is no address added.

Version of the wallet. 0.11.2 downloaded from the Chrome store. 
Chrome version: Version 98.0.4758.109 (Official Build) (arm64)

In later Tally revisions (https://github.com/tallycash/extension/suites/5464519068/artifacts/173930064)  downloaded from GH it's working again.

Logs below 

### Version

Community Edition v0.11.2

### Relevant log output

```shell
background.js:77587  ❌ Tally error @ 2022-02-28T12:58:36.539Z
background.js:77588 Async thunk failed TypeError: Cannot read properties of null (reading 'deriveAddress')
    at background.js:97002:37
    at background.js:5597:22
    at Array.map (<anonymous>)
    at Emittery.emit (background.js:5595:50)
    at async background.js:95189:7
    at async background.js:94687:18
genericLogger @ background.js:77588
background.js:77587  ❌ Tally error @ 2022-02-28T12:58:37.195Z
background.js:77588 Async thunk failed TypeError: Cannot read properties of null (reading 'deriveAddress')
    at background.js:97002:37
    at background.js:5597:22
    at Array.map (<anonymous>)
    at Emittery.emit (background.js:5595:50)
    at async background.js:95189:7
    at async background.js:94687:18
genericLogger @ background.js:77588
background.js:77587  ❌ Tally error @ 2022-02-28T12:58:37.708Z
background.js:77588 Async thunk failed TypeError: Cannot read properties of null (reading 'deriveAddress')
    at background.js:97002:37
    at background.js:5597:22
    at Array.map (<anonymous>)
    at Emittery.emit (background.js:5595:50)
    at async background.js:95189:7
    at async background.js:94687:18
genericLogger @ background.js:77588
background.js:77587  ❌ Tally error @ 2022-02-28T12:58:37.857Z
background.js:77588 Async thunk failed TypeError: Cannot read properties of null (reading 'deriveAddress')
    at background.js:97002:37
    at background.js:5597:22
    at Array.map (<anonymous>)
    at Emittery.emit (background.js:5595:50)
    at async background.js:95189:7
    at async background.js:94687:18
genericLogger @ background.js:77588
background.js:77587  ❌ Tally error @ 2022-02-28T12:58:38.006Z
background.js:77588 Async thunk failed TypeError: Cannot read properties of null (reading 'deriveAddress')
    at background.js:97002:37
    at background.js:5597:22
    at Array.map (<anonymous>)
    at Emittery.emit (background.js:5595:50)
    at async background.js:95189:7
    at async background.js:94687:18
genericLogger @ background.js:77588
background.js:77587  ❌ Tally error @ 2022-02-28T12:58:38.172Z
background.js:77588 Async thunk failed TypeError: Cannot read properties of null (reading 'deriveAddress')
    at background.js:97002:37
    at background.js:5597:22
    at Array.map (<anonymous>)
    at Emittery.emit (background.js:5595:50)
    at async background.js:95189:7
    at async background.js:94687:18
```

**Comment by Eastban120** [comment] 2022-03-02 17:01
Exact same thing happened to me on Firefox.
Version of the wallet. 0.11.2 downloaded from Github and installed as described [here](https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/)
Firefox version: Version 97.0.1 runningn on MacOS 10.1.-

https://user-images.githubusercontent.com/68087535/156410309-9c55d4e2-70c5-4128-8b14-6f0f40e586e6.mov

5.7)

**Comment by Naxsun** [comment] 2022-03-02 19:06
Can you share the GitHub download link? Some of the later revisions I've used have it fixed, but these don't have an official version number update yet.

**Comment by Eastban120** [comment] 2022-03-02 19:30
https://github.com/tallycash/extension/releases/download/v0.11.2/firefox.zip

**Comment by Eastban120** [comment] 2022-03-02 20:44
Just tried with v0.12 and worked as intended !

**Comment by mhluongo** [comment] 2022-03-02 21:01
Woot! One more sign off and we can close this then

**Comment by mhluongo** [comment] 2022-03-03 12:19
Awesome, closing er out

**Closed by mhluongo** 2022-03-03 12:19 UTC
Labels: 🐛 bug, 👩‍⚕️ triage
