### ISSUE TITLE
New gas fee editor allows non-numbers as inputs 

### ISSUE THREAD

**Issue by 0xDaedalus** [tallycash/extension#1704] opened 2022-06-30 21:55 UTC
<img width="375" alt="image" src="https://user-images.githubusercontent.com/94649004/176785414-3520056c-38c1-454f-8449-c469ea8a0753.png">

We want the "Must be a number" warning to display in the above case - similar to 

<img width="297" alt="image" src="https://user-images.githubusercontent.com/94649004/176785493-ac842ffc-d4ba-48cc-9d61-7ce71d75a462.png">

**Comment by henryboldi** [comment] 2022-06-30 21:56
This is a duplicate of part of https://github.com/tallycash/extension/issues/1645

Fixed in https://github.com/tallycash/extension/pull/1680

**Closed by henryboldi** 2022-06-30 21:56 UTC
Labels: 🐛 bug
