### ISSUE TITLE
Dapp signing pop-up - 'Reject' button does not work

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#713] opened 2021-12-17 00:45 UTC
Clicking it does not close window. Tested on Balancer, Uniswap, and Yearn.

https://user-images.githubusercontent.com/7005061/146470166-1f1d8195-4f7f-40c7-8e12-58e38a6795d4.mov

https://user-images.githubusercontent.com/7005061/146470190-79981633-6e48-48c6-920f-723f048f5676.mov

**Comment by wojciech-turek** [comment] 2021-12-17 12:40
Tested this with Henry's solution and it indeed closes the window but does not reject the transaction. I wouldn't close the issue before we actually reject.

**Comment by henryboldi** [comment] 2021-12-17 21:28
Duplicate of #690

**Comment by henryboldi** [comment] 2021-12-17 21:29
Closed by @Shadowfiend by #724

**Closed by henryboldi** 2021-12-17 21:29 UTC
Labels: 🐛 bug, 🚨 high severity
