### ISSUE TITLE
Overview showing 0 assets but does show $ balance

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#814] opened 2022-01-09 10:16 UTC
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/929661930103275531

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

I wasn't able to acquire all details yet but the user has added a read-only address. 

### What did not work?

Will try to get more details, but from what I understand the wallet expected balance is not showing. What's also strange is that the overview page shows 0 assets, but it does show a small $ balance. Was not able to reproduce, but screenshot of user below.

<img width="330" alt="Screenshot 2022-01-09 at 11 11 10" src="https://user-images.githubusercontent.com/71384922/148678089-ab9fae0b-2e1f-44f3-ae39-643ddb0bf678.png">

### Version

Community Edition v0.10.1

**Comment by mr-michael** [comment] 2022-01-14 21:16
I've asked user if they are able to provide addy

**Comment by fasteater** [comment] 2022-01-15 22:23
I have a similar issue, just downloaded the wallet, my balance is showing as 0 incorrectly. Plus I should have more assets then listed.
<img width="368" alt="Screen Shot 2022-01-16 at 9 22 45 am" src="https://user-images.githubusercontent.com/49999458/149639506-39188a97-94a4-4a8c-bcc5-895131bce47a.png">

**Comment by bsklwd2** [comment] 2022-01-16 13:13
![image](https://user-images.githubusercontent.com/84885873/149661317-935669c3-ad47-416f-bc1e-611518a97719.png)
![image](https://user-images.githubusercontent.com/84885873/149661341-768fd292-7198-4f16-8dc2-af16aa6785e5.png)
I recharged into the wallet but the assets are not displayed! There are balance tips on another feature page! I cannot transfer money or do anything! It should be that my system is too old!

**Comment by Naxsun** [comment] 2022-01-17 17:43
@bsklwd2 would you be able to provide the wallet address (0x...) where you observed this bug?

**Comment by bsklwd2** [comment] 2022-01-18 10:56
> @bsklwd2你能提供你观察到这个错误的钱包地址（0x ...）吗？

0x80645f5fB17d75ACa9664A05130E0B33F8Be6366

**Comment by SJQuality** [comment] 2022-05-13 19:29
Not able to reproduce either. It's been a while. Closing, but I'll keep an eye on it.

**Closed by SJQuality** 2022-05-13 19:29 UTC
Labels: 🐛 bug, 👩‍⚕️ triage, ⚠️ medium severity, :video_game: Community Bug
