### ISSUE TITLE
UI tries to unlock KeyringService twice

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#1213] opened 2022-03-21 13:35 UTC
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/954648702784520232

### What browsers are you seeing the problem on?

Brave

### What were you trying to do?

Unlock the wallet

### What did not work?

The wallet thinks it's already unlocked and gives the user an 'Incorrect Password' message.

Logs of a different user than above linked message below, removed intermediate area of logs because below field is limited. Can share the full logs separately.

### Version

Community Edition v0.12.1

### Relevant log output

```shell
logger.tss:65 Async thunk failed Error: KeyringService is already unlocked!
    at KeyringService.unlock (index.tss:161:13)
    at main.tss:914:33
    at index.jss:306:13
    at Array.map (<anonymous>)
    at Emittery.emit (index.jss:304:23)
    at async keyrings.tss:146:3
    at async utils.tss:129:9
genericLogger @ logger.tss:65
error @ logger.tss:106
(anonymous) @ utils.tss:131
await in (anonymous) (async)
(anonymous) @ redux-toolkit.esm.jss:1112
step @ redux-toolkit.esm.jss:38
(anonymous) @ redux-toolkit.esm.jss:19
(anonymous) @ redux-toolkit.esm.jss:87
__async @ redux-toolkit.esm.jss:69
(anonymous) @ redux-toolkit.esm.jss:1096
(anonymous) @ redux-toolkit.esm.jss:1095
(anonymous) @ index.jss:8
(anonymous) @ alias.jss:20
dispatchResponse @ wrapStore.jss:94
(anonymous) @ serialization.jss:38
logger.tss:60  🐛 Tally debug @ 2022-03-21T11:07:21.027Z
geturl.jss:30          GET https://api.blocknative.com/gasprices/blockprices 429
(anonymous) @ geturl.jss:30
(anonymous) @ geturl.jss:8
geturl_awaiter @ geturl.jss:4
getUrl @ geturl.jss:13
(anonymous) @ index.jss:169
(anonymous) @ index.jss:8
web_lib_esm_awaiter @ index.jss:4
(anonymous) @ index.jss:165
_fetchData @ index.jss:164
lib_esm_fetchJson @ index.jss:311
getBlockPrices @ index.tss:101
getBlockPrices @ gas.tss:28
(anonymous) @ index.tss:659
pollBlockPrices @ index.tss:658
handler @ index.tss:188
handleAlarm @ base.tss:155
geturl.jss:30          GET https://api.blocknative.com/gasprices/blockprices 429
(anonymous) @ geturl.jss:30
(anonymous) @ geturl.jss:8
geturl_awaiter @ geturl.jss:4
getUrl @ geturl.jss:13
(anonymous) @ index.jss:169
fulfilled @ index.jss:5
Promise.then (async)
step @ index.jss:7
fulfilled @ index.jss:5
Promise.then (async)
step @ index.jss:7
(anonymous) @ index.jss:8
web_lib_esm_awaiter @ index.jss:4
(anonymous) @ index.jss:165
_fetchData @ index.jss:164
lib_esm_fetchJson @ index.jss:311
getBlockPrices @ index.tss:101
getBlockPrices @ gas.tss:28


Skip intermediate log content.


(anonymous) @ index.jss:165
_fetchData @ index.jss:164
lib_esm_fetchJson @ index.jss:311
getBlockPrices @ index.tss:101
getBlockPrices @ gas.tss:28
(anonymous) @ index.tss:659
pollBlockPrices @ index.tss:658
handler @ index.tss:188
handleAlarm @ base.tss:155
logger.tss:60  ❌ Tally error @ 2022-03-21T11:08:47.498Z
logger.tss:65 Async thunk failed TypeError: Cannot read properties of undefined (reading 'forEach')
    at KeyringService.unlock (index.tss:187:33)
    at async main.tss:913:46
    at async Promise.all (index 0)
    at async Emittery.emit (index.jss:302:9)
    at async keyrings.tss:146:3
    at async utils.tss:129:9
genericLogger @ logger.tss:65
error @ logger.tss:106
(anonymous) @ utils.tss:131
logger.tss:60  ❌ Tally error @ 2022-03-21T11:08:51.209Z
logger.tss:65 Async thunk failed TypeError: Cannot read properties of undefined (reading 'forEach')
    at KeyringService.unlock (index.tss:187:33)
    at async main.tss:913:46
    at async Promise.all (index 0)
    at async Emittery.emit (index.jss:302:9)
    at async keyrings.tss:146:3
    at async utils.tss:129:9
genericLogger @ logger.tss:65
error @ logger.tss:106
(anonymous) @ utils.tss:131
geturl.jss:30          GET https://api.blocknative.com/gasprices/blockprices 429
(anonymous) @ geturl.jss:30
(anonymous) @ geturl.jss:8
geturl_awaiter @ geturl.jss:4
getUrl @ geturl.jss:13
(anonymous) @ index.jss:169
fulfilled @ index.jss:5
Promise.then (async)
step @ index.jss:7
fulfilled @ index.jss:5
Promise.then (async)
step @ index.jss:7
fulfilled @ index.jss:5
Promise.then (async)
step @ index.jss:7
fulfilled @ index.jss:5
Promise.then (async)
step @ index.jss:7
fulfilled @ index.jss:5
Promise.then (async)
step @ index.jss:7
fulfilled @ index.jss:5
Promise.then (async)
step @ index.jss:7
fulfilled @ index.jss:5
```

**Comment by Shadowfiend** [comment] 2022-03-21 13:44
As noted by @mhluongo elsewhere, the fix here should just be to change the `unlock` method on `KeyringService` to return true rather than throwing if the service is already unlocked:

https://github.com/tallycash/extension/blob/14be0d9e003552dc9a4dbc6f1510886ee3697272/background/services/keyring/index.ts#L160-162

This should be reflected in a tests update as well. 

We should still log that a double unlock occurred, as it indicates a state sync issue somewhere.

**Comment by jagodarybacka** [comment] 2022-06-09 12:56
Is there any way to reproduce this bug "in the wild" without changing the code as in #1217 ?
Is it even still bugged? @0xDaedalus why this issue is still open after your PR has been merged? If we can't reproduce it then maybe just close the task?

**Comment by 0xDaedalus** [comment] 2022-06-09 13:16
I think we can probably safely remove this.  I think we suspected there might be a problem on the UI side causing this to happen but I'm not sure that that's the case anymore. cc @henryboldi in case he has any context - otherwise lets close tomorrow.

**Comment by Naxsun** [comment] 2022-06-10 08:09
There were still reports with logs with a similar error message after the PR merge. I don't know if the effect for the user was exactly the same. But for example from the logs of https://github.com/tallycash/extension/issues/1380

KeyringService.unlock
KeyringService is already unlocked!

**Comment by jagodarybacka** [comment] 2022-06-10 10:10
@Naxsun in the linked PR we were supposed to keep logging the warning so I guess that is ok. The question is if there is anything wrong with UI flow right now. And what users are doing exactly to get that warning. Is it possible to find the discord discussions about this problem?

**Comment by Naxsun** [comment] 2022-06-10 10:37
Yeah this is 1 that I could dig up quickly. https://discord.com/channels/808358975287722045/888500174685614090/969599886863519815

**Comment by jagodarybacka** [comment] 2022-06-15 09:50
I've tried multiple combinations of a refresh, browser restart and background script reload and I can't find a way to get `KeyringService is already unlocked!` warning in the logs. I think we can close this task right now, if someone will find steps to reproduce the warning we can reopen it.

Closing as `can't reproduce`

**Closed by jagodarybacka** 2022-06-15 09:50 UTC
Labels: 🐛 bug, :video_game: Community Bug
