### ISSUE TITLE
Not able to send ETH - different than 1207

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#1208] opened 2022-03-21 10:14 UTC
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/955407283729342514

### What browsers are you seeing the problem on?

Brave

### What were you trying to do?

The user tried to send ETH

I tried myself on Brave and experienced the same issue.

### What did not work?

When hitting send a red bar blinks at the top, and you end up on the send screen again. Hitting send again makes it go to a blank screen. Screen recording on Discord through link https://discord.com/channels/808358975287722045/888500174685614090/955407283729342514

A Discord user and myself both have the same issue, both using Brave & extension 0.12.1. Unfortunately the wallet extension auto updated to 0.12.2 afterwards before I was able to copy the logs.

After the update sending works again.

User report: https://discord.com/channels/808358975287722045/888500174685614090/954648702784520232

### Version

Community Edition v0.12.1

**Comment by henryboldi** [comment] 2022-03-22 05:56
I've reproduced this in  v0.12.2 in Brave. Looks like it's hitting a `return <></>` somewhere important since the` popup.html` console is blank, and none of the background errors look relevant.

**Comment by Shadowfiend** [comment] 2022-03-22 10:38
I *believe* this should have been fixed in #1163.

**Comment by greg-nagy** [comment] 2022-05-02 14:47
This is indeed fixed in #1163 closing this

**Closed by greg-nagy** 2022-05-02 14:47 UTC
Labels: 🐛 bug, 👩‍⚕️ triage, 🚨 high severity
