### ISSUE TITLE
0x...0x read only address & balance update bug

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#2093] opened 2022-09-01 06:44 UTC
### Discord Discussion Link

na

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

The user wanted to see his balances on mainnet and Polygon.

### What did not work?

(meanwhile this user re-installed 0.15.0 and the issue is fixed in the new install)

Balances for both mainnet and Polygon weren't updated. Both ETH and MATIC, as well as ERC20.
Address: 0x25eef1d3c241f1ffed1b421d55b1ee0a257cf6c2

Logs:
[logs_v0_14_7__2022-08-31T10_53_1309_30 (2).txt](https://github.com/tallycash/extension/files/9467452/logs_v0_14_7__2022-08-31T10_53_1309_30.2.txt)

![image](https://user-images.githubusercontent.com/71384922/187848899-b38e1937-c902-4af6-a486-4545efc901a6.png)

Also the user had a 0x...0x address as read only account, and is unsure how it got there. Didn't add it on purpose.

![image](https://user-images.githubusercontent.com/71384922/187849126-162cdd5c-a4e9-4718-ae52-126829732ae0.png)

### Version

v0.14.7

**Comment by jagodarybacka** [comment] 2022-09-06 12:27
I'm not able to reproduce it, never seen read only account that was resolved like that. Looking at the logs - balance updates, at least for that read only account, were not successful because address was in a wrong format. There is nothing recorded about the imported account there. As this is resolved by reinstall I would close it for now.

**Closed by jagodarybacka** 2022-09-06 12:27 UTC
Labels: 🐛 bug, 👩‍⚕️ triage, 🚨 high severity
