### ISSUE TITLE
dApp transactions not broadcasted (Yearn, Aave, Compound...)

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#2053] opened 2022-08-28 13:57 UTC
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/1013054391495966771

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Set-up a transaction on dApps

### What did not work?

Transactions failed to broadcast. No logs received yet, requested:

Screen recording: https://discord.com/channels/808358975287722045/888500174685614090/1013054391495966771

I think it's version 0.14.7 but I've asked the user to confirm.

### Version

Community Edition v0.14.7

**Comment by jagodarybacka** [comment] 2022-09-14 11:20
Cannot reproduce, yearn and aave are working fine, I guess this was a problem due to either nonce issue or stuck sign button, both fixed on `main`

**Closed by jagodarybacka** 2022-09-14 11:20 UTC
Labels: 🐛 bug, 🚨 high severity
