### ISSUE TITLE
Matic should not show up in the asset list just because it's base asset for a network that we support

### ISSUE THREAD

**Issue by greg-nagy** [tallycash/extension#1652] opened 2022-06-21 17:50 UTC
If I am on mainnet and my matic account is 0 on mainnet, it shouldn't show up as an asset

**Comment by 0xDaedalus** [comment] 2022-06-24 13:44
Duplicate of https://github.com/tallycash/extension/issues/1614

**Closed by 0xDaedalus** 2022-06-24 13:44 UTC
