### ISSUE TITLE
Transaction history / Activity not loading

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#560] opened 2021-12-10 21:33 UTC
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

-

### What did not work?

Neither global Activity nor asset-specific txn history, for ETH or tokens. Perpetually in loading state even after an hour. For this wallet, there are only 2 all-time txns.

<img width="365" alt="Screen Shot 2021-12-10 at 4 32 24 PM" src="https://user-images.githubusercontent.com/7005061/145643954-408162fb-2e06-4251-b516-94b91f10c856.png">

<img width="355" alt="Screen Shot 2021-12-10 at 4 32 17 PM" src="https://user-images.githubusercontent.com/7005061/145643955-a7f71bc4-b34c-4cf3-a274-0332287a26a8.png">

**Comment by mhluongo** [comment] 2021-12-13 18:33
@henryboldi could this be because the loader shows forever if no activity is reported, even if that's accurate? Maybe we should have the background send a "INITIAL_ACTIVITY_LOADED" action or something?

**Comment by creckhow** [comment] 2021-12-15 02:17
my experience with this...on read only accounts, eventually the activity tab stopped beach balling (15-30 mins later) BUT it only showed me ETH tx history, nothing for other tokens like KEEP. 

AND for the wallet that I ended up importing (after having it read only for 30 mins and the activity never loading), the activity page only ended up showing me the activity from testing that day, the previous wallet activity never showed up. Not sure if that's a feature not a bug...

**Comment by mhluongo** [comment] 2021-12-15 15:48
Closed by #643

**Closed by mhluongo** 2021-12-15 15:48 UTC
Labels: 🐛 bug, 👩‍⚕️ triage, 🚨 high severity
