### ISSUE TITLE
UI allows sending a token tx, shows up as pending ETH tx in activity

### ISSUE THREAD

**Issue by creckhow** [tallycash/extension#631] opened 2021-12-15 01:45 UTC
<img width="374" alt="Screen Shot 2021-12-14 at 6 45 53 PM" src="https://user-images.githubusercontent.com/74791142/146106801-2801ea22-52eb-49a3-ab34-6769e476d341.png">
I'm able to click through to send KEEP. 

The asset logo reverted to a generic K from the Keep logo at this screen. 

I was able to enter 100 KEEP and hit send. It showed me this screen after hitting send (showing the original amount of KEEP that was in the wallet): 

<img width="385" alt="Screen Shot 2021-12-14 at 6 48 39 PM" src="https://user-images.githubusercontent.com/74791142/146107088-1fb5273e-9f57-4a62-9999-e9e112755066.png">

Then under the activity tag, this attempted KEEP tx surprisingly shows up ... but it says it's a pending 100 ETH tx, not KEEP. 
<img width="382" alt="Screen Shot 2021-12-14 at 8 34 20 PM" src="https://user-images.githubusercontent.com/74791142/146107374-5e00d2d6-e7d6-4454-bbd9-7ee70efdbeb6.png">

And when you click into the tx, you see the same type of detail screen a failed ETH tx shows you...with a [bad etherscan link](https://etherscan.io/tx/0x0e64e5004245663006ccbe020383b381cbb7d6b47f4c1dbde3679e43103abdb2)

<img width="380" alt="Screen Shot 2021-12-14 at 8 43 04 PM" src="https://user-images.githubusercontent.com/74791142/146107471-31a2dd21-b29f-4881-87bc-fb4b2fe80532.png">

**Comment by henryboldi** [comment] 2021-12-15 01:46
Mostly a duplicate of #626

**Comment by henryboldi** [comment] 2021-12-15 01:46
Duplicate of #626

**Comment by henryboldi** [comment] 2021-12-15 01:47
(Granted, #626 doesn't mention it showing up as a pending ETH tx in activity)

**Comment by mhluongo** [comment] 2021-12-15 01:58
Pretty sure it actually sends ETH... making this a showstopper :grimacing:

**Comment by creckhow** [comment] 2021-12-15 01:59
how can you tell it's "actually" sending ETH? since sending ETH doesn't actually send ETH....

**Comment by mhluongo** [comment] 2021-12-15 02:01
If it made it to pending tx that strongly implies a tx was signed :shrug:

**Closed** 2021-12-15 15:48 UTC
Labels: 🐛 bug, 🚨 high severity
