### ISSUE TITLE
CPU performance regression as of `v0.12.2`

### ISSUE THREAD

**Issue by mhluongo** [tallycash/extension#1216] opened 2022-03-21 15:31 UTC
Initially [reported on Discord](https://discord.com/channels/808358975287722045/893564740427743292/954688571757985812)

![unknown](https://user-images.githubusercontent.com/427505/159296097-b5ad6d2e-c770-4935-946d-cd4b0c20b7da.png)

More details from Discord

> GM wanted to reply to this; I ran a series of tests to analyze cpu usage, on my Macbook in v12.2 and v12.1 Looking at A:Google Chrome and B:Google Chrome Helper (renderer) status. In v12.2 I am seeing much higher usage spikes (171 -210% for both a/b) whereas v12.1 usage spikes to (28-40 % for either a/b) I tried loading/creating/refreshing seed wallets, receiving ETH, and running Eth/KEEP swaps to look for a spike correlation. Nothing pointed directly to these activities.

**Comment by greg-nagy** [comment] 2022-05-02 14:43
- We have fixed the high cpu load from account balance checks (batch the indexeddb writes)

The following tickets and PRs have the full picture to solve the most prominent issues 
- #1351 
- #1363 
- #1376 

re:batching middleware

This approach did not work, but I have something similar with redux store enhancers in #1296 just need to find the time to finish it

anyhow closing this as duplicate of above

**Closed by greg-nagy** 2022-05-02 14:43 UTC
Labels: 🚨 high severity
