### ISSUE TITLE
nothing happens when you click "how do I find the seed"? 

### ISSUE THREAD

**Issue by creckhow** [tallycash/extension#632] opened 2021-12-15 01:50 UTC
Here, clicking "how do I find the seed?" under the import wallet button when importing a wallet does zilch. 

<img width="387" alt="Screen Shot 2021-12-14 at 6 26 46 PM" src="https://user-images.githubusercontent.com/74791142/146108083-d8ca019a-557b-40d6-9a63-77d5a5c8fbc4.png">

Also shouldn't it be "recovery phrase", aren't we trying to phase out "seed" language?

**Comment by henryboldi** [comment] 2021-12-16 18:15
Fixed by https://github.com/tallycash/extension/commit/2302045cf4691e598b9ad6bc0841bee815590644

**Closed by henryboldi** 2021-12-16 18:15 UTC
Labels: 🐛 bug, 🤷 low severity

**Comment by henryboldi** [comment] 2021-12-16 18:20
Duplicate of #579
